blockchain:
  difficulty: 3
  bootstrap-nodes:
    - "http://localhost:8081"
    - "http://localhost:8082"
  network:
    known-peers:
      - "http://localhost:8081"

node:
  identity:
    private-key: ${NODE_PRIVATE_KEY:PON_AQUI_UNA_CLAVE_PRIVADA_DE_PRUEBA_EN_BASE64}
    public-key: ${NODE_PUBLIC_KEY:PON_AQUI_UNA_CLAVE_PUBLICA_DE_PRUEBA_EN_BASE64}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always